In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/Salaries.csv')

In [5]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

Find The Occurrence Of the Employee Names

In [6]:
employee_name_counts = df['EmployeeName'].value_counts().head(5)
print(employee_name_counts)

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

 Find The Number Of Unique Jobs Titles

In [7]:
unique_job_titles = df['JobTitle'].nunique()
print(unique_job_titles)

2159

 Find The Total Number Of Job Titles Contain captain

In [8]:
captain_jobs = df[df['JobTitle'].str.contains('Captain', case=False)]['JobTitle'].count()
print(captain_jobs)

552

Display All the Employee Names from Fire Department

In [9]:
fire_department_employees = df[df['JobTitle'].str.contains('Fire Department', case=False)]['EmployeeName']
print(fire_department_employees)

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: object

 Find The Minimum, Maximum and Average BasePay

In [10]:
min_basepay = df['BasePay'].min()
max_basepay = df['BasePay'].max()
avg_basepay = df['BasePay'].mean()

print("Minimum BasePay:", min_basepay)
print("Maximum BasePay:", max_basepay)
print("Average BasePay:", avg_basepay)

Minimum BasePay: -166.01
Maximum BasePay: 319275.01
Average BasePay: 66325.4488404877

 Replace â€˜Not providedâ€™ in EmployeeName Column to Nan

In [11]:
df['EmployeeName'] = df['EmployeeName'].replace('Not provided', np.nan)

In [14]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

 Drop The Rows Having 5 Missing Values

In [12]:
df = df.dropna(thresh=len(df.columns) - 4)
# Keep rows with at least (total columns - 4) non-missing values

In [15]:
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

Find The Job Title Of ALBERT PARDINI

In [13]:
albert_job_title = df[df['EmployeeName'] == 'ALBERT PARDINI']['JobTitle'].iloc[0]
print(albert_job_title)

CAPTAIN III (POLICE DEPARTMENT)

 How Much ALBERT PARDINI makes (include Benefits)

In [17]:
albert_total_pay = df[df['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits'].iloc[0]
print(albert_total_pay)

335279.91

Display Name Of The Person Having The Highest Basepay

In [18]:
highest_basepay_person = df.loc[df['BasePay'].idxmax(), 'EmployeeName']
print(highest_basepay_person)

Gregory P Suhr

 Find The average Basepay of all Employees per Year

In [19]:
avg_basepay_per_year = df.groupby('Year')['BasePay'].mean()
print(avg_basepay_per_year)

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

Find Average Basepay Of All Employee Per Job Title

In [20]:
avg_basepay_per_job = df.groupby('JobTitle')['BasePay'].mean()
print(avg_basepay_per_job)

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2158, dtype: float64

Find The Average Basepay of All Employee Having job Title Accountant

In [21]:
accountant_avg_basepay = df[df['JobTitle'] == 'Accountant']['BasePay'].mean()
print(accountant_avg_basepay)

nan

Five Most Common Jobs

In [22]:
most_common_jobs = df['JobTitle'].value_counts().head(5)
print(most_common_jobs)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64